"""empty message

Revision ID: 637d302b8941
Revises: a564a0ad173d
Create Date: 2025-08-22 22:18:07.363326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637d302b8941'
down_revision = 'a564a0ad173d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_post_id_fkey', 'user', ['post_id'], ['id'])

    # ### end Alembic commands ###
