"""empty message

Revision ID: b29906f86913
Revises: 310220774755
Create Date: 2025-08-20 18:14:47.989429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29906f86913'
down_revision = '310220774755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=150), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'author_id', 'post_id')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_to_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=False))

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('user_to_id')
        batch_op.drop_column('user_from_id')

    op.drop_table('comment')
    # ### end Alembic commands ###
